replicaCount: 1
namespace: dev

image:
  repository: mysql
  tag: "8.2"

service:
  name: mysql-service
  type: ClusterIP
  port: 3306

pvc:
  size: 5G
  mode: ReadWriteOnce

config:
  mysqlpass: lxeh9823ryf3h
